### ISSUE TITLE
Fails to compile on Ubuntu via cargo install

### ISSUE THREAD

**Issue by alexkirsz** [sozu-proxy/sozu#657]
I'm getting the following two errors when trying to compile on Ubuntu 20.04.1 (`cargo install sozu`):

```
error[E0308]: mismatched types
    --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.11.0/src/http.rs:1270:38
     |
1270 |     if let Err(e) = scm.send_listeners(Listeners {
     |  ______________________________________^
1271 | |     http: Vec::new(),
1272 | |     tls:  Vec::new(),
1273 | |     tcp:  Vec::new(),
1274 | |   }) {
     | |___^ expected `&sozu_command::scm_socket::Listeners`, found struct `sozu_command::scm_socket::Listeners`
     |
help: consider borrowing here
     |
1270 |   if let Err(e) = scm.send_listeners(&Listeners {
1271 |     http: Vec::new(),
1272 |     tls:  Vec::new(),
1273 |     tcp:  Vec::new(),
1274 |   }) {
     |

error[E0308]: mismatched types
   --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/sozu-lib-0.11.0/src/server.rs:820:39
    |
820 |     let res = self.scm.send_listeners(listeners);
    |                                       ^^^^^^^^^
    |                                       |
    |                                       expected `&sozu_command::scm_socket::Listeners`, found struct `sozu_command::scm_socket::Listeners`
    |                                       help: consider borrowing here: `&listeners`
```

The version published on crates.io is `0.11.0` but I see that the latest version on Github is `0.11.50`.

**Comment by Geal** [comment]
right, I did not publish a new version in a while, could you try now? All sozu crates are at 0.11.50 now

**Comment by alexkirsz** [comment]
It compiled properly 👍 Thanks!
