### ISSUE TITLE
Versions 0.14.X don't build on MacOS ARM but  0.13.6 works

### ISSUE THREAD

**Issue by pims** [sozu-proxy/sozu#865]
Hi there 👋 ,

Very cool project.
I tried to install sozu on MacOS (ARM) but ran into compile issues for both `0.14.1` and `0.14.2`.
I tried on both nightly (1.68) and stable (1.65) without much success.

fwiw, it builds successfully on `.0.13.6`:
```
$ sozu % git checkout 0.13.6
Previous HEAD position was b5dde9d0 Release: v0.14.1
HEAD is now at e4e74882 v0.13.6
$ sozu % cargo build --locked
…
$  Finished dev [unoptimized + debuginfo] target(s) in 2.97s
```

Here are the compile errors I see on the `0.14.X` tags:
```
warning: `sozu-lib` (lib) generated 2 warnings
   Compiling jemallocator v0.5.0
error[E0412]: cannot find type `StartupError` in this scope
   --> bin/src/main.rs:272:52
    |
272 | fn update_process_limits(_: &Config) -> Result<(), StartupError> {
    |                         -                          ^^^^^^^^^^^^ not found in this scope
    |                         |
    |                         help: you might be missing a type parameter: `<StartupError>`

warning: unused import: `bail`
  --> bin/src/worker.rs:21:14
   |
21 | use anyhow::{bail, Context};
   |              ^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `bail`
  --> bin/src/main.rs:39:14
   |
39 | use anyhow::{bail, Context};
   |              ^^^^

error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> bin/src/command/mod.rs:303:40
    |
303 |         let executable_path = unsafe { get_executable_path()? };
    |                                        ^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `std::string::String`
    |
    = help: the trait `Try` is not implemented for `std::string::String`

error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> bin/src/command/mod.rs:519:40
    |
519 |         let executable_path = unsafe { get_executable_path()? };
    |                                        ^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `std::string::String`
    |
    = help: the trait `Try` is not implemented for `std::string::String`

error[E0599]: no method named `with_context` found for struct `std::string::String` in the current scope
   --> bin/src/main.rs:127:47
    |
127 |     let path = unsafe { get_executable_path().with_context(|| "Could not get executable path")? };
    |                                               ^^^^^^^^^^^^ method not found in `std::string::String`

Some errors have detailed explanations: E0277, E0412, E0599.
For more information about an error, try `rustc --explain E0277`.
warning: `sozu` (bin "sozu") generated 2 warnings
error: could not compile `sozu` due to 4 previous errors; 2 warnings emitted
```

**Comment by FlorentinDUBOIS** [comment]
Hello @pims, I am glad to see you there, you teach me that Sōzu is able to compile on Darwin architecture, furthermore in ARM which is quite cool! We do not have plan to support Darwin for now as the design strongly rely on Linux's glibc and kernel features. Even though, we will support the ARM architecture in future releases.

**Comment by pims** [comment]
@FlorentinDUBOIS Thanks for the quick reply.
I'm a bit confused as I see (tentative?) support for MacOS is `bin/worker.rs`

```
#[cfg(target_os = "macos")]
extern "C" {
    pub fn _NSGetExecutablePath(buf: *mut c_char, size: *mut u32) -> i32;
}

#[cfg(target_os = "macos")]
…
```

I'm fairly new to Rust, so I might be a misunderstanding on my part.
Not gonna lie, it'd be nice to be able to run Sōzu on MacOS even if it's just for tinkering 😄

**Comment by pims** [comment]
Took a stab at it: https://github.com/sozu-proxy/sozu/pull/869

**Comment by pims** [comment]
Fixed in https://github.com/sozu-proxy/sozu/pull/869

**Comment by matthiasg** [comment]
sozu v0.15.16 doesnt install anymore on Apple M1 Max (Sonoma 14.0) due to a `kawa` issue trying to use x86_64 architecture.

```
Compiling kawa v0.6.4
error[E0432]: unresolved import `std::arch::x86_64`
   --> /Users/mgt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kawa-0.6.4/src/protocol/utils.rs:127:32
    |
127 |                 use std::arch::x86_64::{
    |                                ^^^^^^ could not find `x86_64` in `arch`
    |
   ::: /Users/mgt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kawa-0.6.4/src/protocol/h1/parser/primitives.rs:93:1
    |
93  | compile_lookup!(pub tchar => [0x00..0x20, '('..')', '['..']', '{', '}', ',', ':'..'@', 0x7F..LAST_INVALID_CHAR...
    | --------------------------------
    ....
    ```

**Comment by extrawurst** [comment]
@matthiasg did you get it to compile after all?
